# Generated by Django 4.2.7 on 2026-07-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("param", "Параметр"),
                            ("kpi", "KPI"),
                            ("mech", "Механизм"),
                            ("fail", "Деградация"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=50)),
                ("color", models.CharField(default="#135BEC", max_length=20)),
                ("is_dashed", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="graph.graphnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="graph.graphnode",
                    ),
                ),
            ],
        ),
    ]
