# Generated by Django 4.2.7 on 2026-07-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(default="planning", max_length=50)),
                ("progress", models.IntegerField(default=0)),
                ("available_resources", models.TextField(blank=True)),
                ("checklist", models.JSONField(default=list)),
                ("success_probability", models.FloatField(default=0.5)),
                ("optimal_scenario", models.TextField(blank=True)),
                ("pessimistic_scenario", models.TextField(blank=True)),
                ("optimistic_scenario", models.TextField(blank=True)),
                ("risks", models.TextField(blank=True)),
                ("risk_mitigation", models.TextField(blank=True)),
                (
                    "analogs",
                    models.TextField(
                        blank=True,
                        help_text="Конкретные примеры аналогов с названиями компаний, проектов или DOI",
                    ),
                ),
                ("resources_needed", models.TextField(blank=True)),
                ("business_roi", models.FloatField(default=0.0)),
                (
                    "business_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("business_payback", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
