# Generated by Django 4.2.7 on 2026-07-04 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hypotheses", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="hypothesis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hypotheses.hypothesis",
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="objects.researchobject",
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
