# Generated by Django 4.2.7 on 2026-07-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Идея"),
                            ("validation", "Валидация ИИ"),
                            ("experiment", "НИОКР / Эксперимент"),
                            ("completed", "Завершено"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                ("novelty_score", models.PositiveSmallIntegerField(default=50)),
                ("feasibility_score", models.FloatField(default=0.5)),
                (
                    "research_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "economic_benefit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "payback_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("roi", models.FloatField(blank=True, null=True)),
                ("complexity_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheses",
                        to="objects.researchobject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=50)),
                ("risk_level", models.CharField(max_length=20)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_steps",
                        to="hypotheses.hypothesis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="Текст доказательства или обоснования"),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Источник доказательства (статья, патент, отчёт)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="hypotheses.hypothesis",
                    ),
                ),
            ],
        ),
    ]
